package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.ContactJournal;
import at.easydiet.model.DietParameter;
import at.easydiet.model.DietPlan;
import at.easydiet.model.DietTreatment;
import at.easydiet.model.DietTreatmentSystemUser;
import at.easydiet.model.NutritionProtocol;
import at.easydiet.model.PatientState;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DietTreatmentBo generated by hbm2java
 */
public class DietTreatmentBo  implements java.io.Serializable, Saveable {

     private TreatmentStateBo treatmentState;
     private DietTreatment _DietTreatment;

    private DietTreatmentBo() {
    }

    public DietTreatmentBo(DietTreatment dietTreatment){
        this._DietTreatment=dietTreatment;
    }
	
    public DietTreatmentBo(Date start, int duration, String name, TreatmentStateBo treatmentStateBo) {
        this(new DietTreatment(start, duration, name, treatmentStateBo.getTreatmentState()));
    }
    public DietTreatmentBo(Date start, int duration, String name, Set<NutritionProtocolBo> nutritionProtocolsBo, Set<DietPlanBo> dietPlansBo, Set<DietParameterBo> dietParametersBo, Set<PatientStateBo> patientStatesBo, Set<DietTreatmentSystemUserBo> dietTreatmentSystemUsersBo, Set<ContactJournalBo> contactJournalsBo, TreatmentStateBo treatmentStateBo) {
       this(start, duration, name, treatmentStateBo);

        for (NutritionProtocolBo nutritionProtocolBo : nutritionProtocolsBo) {
            this._DietTreatment.getNutritionProtocols().add(nutritionProtocolBo.getNutritionProtocol());
        }

        for (DietPlanBo dietPlanBo : dietPlansBo) {
            this._DietTreatment.getDietPlans().add(dietPlanBo.getDietPlan());
        }

        for (DietParameterBo dietParameterBo : dietParametersBo) {
            this._DietTreatment.getDietParameters().add(dietParameterBo.getDieDietParameter());
        }

        for(PatientStateBo patientStateBo: patientStatesBo){
            this._DietTreatment.getPatientStates().add(patientStateBo.getPatientState());
        }

        for(DietTreatmentSystemUserBo dietTreatmentSystemUserBo: dietTreatmentSystemUsersBo){
            this._DietTreatment.getSystemUsers().add(dietTreatmentSystemUserBo.getDietTreatmentSystemUser());
        }

        for(ContactJournalBo contactJournalBo: contactJournalsBo){
            this._DietTreatment.getContactJournals().add(contactJournalBo.getContactjournal());
        }
    }
   
    public long getDietTreatmentId() {
        return this.getDietTreatment().getDietTreatmentId();
    }
    
    public void setDietTreatmentId(long dietTreatmentId) {
        this.getDietTreatment().setDietTreatmentId(dietTreatmentId);
    }
    public Date getStart() {
        return this.getDietTreatment().getStart();
    }
    
    public void setStart(Date start) {
        this.getDietTreatment().setStart(start);
    }
    public int getDuration() {
        return this.getDietTreatment().getDuration();
    }
    
    public void setDuration(int duration) {
        this.getDietTreatment().setDuration(duration);
    }
    public String getName() {
        return this.getDietTreatment().getName();
    }
    
    public void setName(String name) {
        this.getDietTreatment().setName(name);
    }

    public Set<NutritionProtocolBo> getNutritionProtocols() {
        Set<NutritionProtocolBo> temp = new HashSet<NutritionProtocolBo>(this._DietTreatment.getNutritionProtocols().size());
        for (NutritionProtocol nutritionProtocol : this._DietTreatment.getNutritionProtocols()) {
            temp.add(new NutritionProtocolBo(nutritionProtocol));
        }
        return temp;
    }
    
    public void setNutritionProtocols(Set<NutritionProtocolBo> nutritionProtocolsBo) {
        for (NutritionProtocolBo nutritionProtocolBo : nutritionProtocolsBo) {
            this._DietTreatment.getNutritionProtocols().add(nutritionProtocolBo.getNutritionProtocol());
        }
    }
    public Set<DietPlanBo> getDietPlans() {
        Set<DietPlanBo> temp= new HashSet<DietPlanBo>(this._DietTreatment.getDietPlans().size());
        for (DietPlan dietPlan : this._DietTreatment.getDietPlans()) {
            temp.add(new DietPlanBo(dietPlan));
        }
        return temp;
    }
    
    public void setDietPlans(Set<DietPlanBo> dietPlansBo) {
        for (DietPlanBo dietPlanBo : dietPlansBo) {
            this._DietTreatment.getDietPlans().add(dietPlanBo.getDietPlan());
        }
    }
    public Set<DietParameterBo> getDietParameters() {
        Set<DietParameterBo> temp = new HashSet<DietParameterBo>(this._DietTreatment.getDietParameters().size());
        for (DietParameter dietParameter : this._DietTreatment.getDietParameters()) {
            temp.add(new DietParameterBo(dietParameter));
        }
        return temp;
    }
    
    public void setDietParameters(Set<DietParameterBo> dietParametersBo) {
        for (DietParameterBo dietParameterBo : dietParametersBo) {
            this._DietTreatment.getDietParameters().add(dietParameterBo.getDieDietParameter());
        }
    }
    public Set<PatientStateBo> getPatientStates() {
        Set<PatientStateBo> temp = new HashSet<PatientStateBo>(this._DietTreatment.getPatientStates().size());
        for (PatientState patientState : this._DietTreatment.getPatientStates()) {
            temp.add(new PatientStateBo(patientState));
        }
        return temp;
    }
    
    public void setPatientStates(Set<PatientStateBo> patientStatesBo) {
        for(PatientStateBo patientStateBo: patientStatesBo){
            this._DietTreatment.getPatientStates().add(patientStateBo.getPatientState());
        }
    }

    public Set<DietTreatmentSystemUserBo> getDietTreatmentSystemUsersBo() {
        Set<DietTreatmentSystemUserBo> temp = new HashSet<DietTreatmentSystemUserBo>(this._DietTreatment.getSystemUsers().size());
        for (DietTreatmentSystemUser dietTreatmentSystemUser : this._DietTreatment.getSystemUsers()) {
            temp.add(new DietTreatmentSystemUserBo(dietTreatmentSystemUser));
        }
        return temp;
    }
    
    public void setDietTreatmentSystemUsersBo(Set<DietTreatmentSystemUserBo> dietTreatmentSystemUsersBo) {
         for(DietTreatmentSystemUserBo dietTreatmentSystemUserBo: dietTreatmentSystemUsersBo){
            this._DietTreatment.getSystemUsers().add(dietTreatmentSystemUserBo.getDietTreatmentSystemUser());
        }
    }

    public Set<ContactJournalBo> getContactJournals() {
        Set<ContactJournalBo> temp = new HashSet<ContactJournalBo>(this._DietTreatment.getContactJournals().size());
        for (ContactJournal contactJournal : this._DietTreatment.getContactJournals()) {
            temp.add(new ContactJournalBo(contactJournal));
        }
        return temp;
    }
    
    public void setContactJournals(Set<ContactJournalBo> contactJournalsBo) {
        for(ContactJournalBo contactJournalBo: contactJournalsBo){
            this._DietTreatment.getContactJournals().add(contactJournalBo.getContactjournal());
        }
    }
    public TreatmentStateBo getTreatmentState() {
        return this.treatmentState;
    }
    
    public void setTreatmentState(TreatmentStateBo treatmentState) {
        this.getDietTreatment().setTreatmentState(treatmentState.getTreatmentState());
        this.treatmentState = treatmentState;
    }

    /**
     * @return the _DietTreatment
     */
    protected DietTreatment getDietTreatment() {
        return _DietTreatment;
    }

    /**
     * @param DietTreatment the _DietTreatment to set
     */
    public void setDietTreatment(DietTreatment DietTreatment) {
        this._DietTreatment = DietTreatment;
    }

    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


