package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.DietTreatmentSystemUser;




/**
 * DietTreatmentSystemUserBo generated by hbm2java
 */
public class DietTreatmentSystemUserBo  implements java.io.Serializable {

     private SystemUserBo _SystemUser;
     private SystemUserFunctionBo _Function;

     private DietTreatmentSystemUser _DietTreatmentSystemUser;

    public DietTreatmentSystemUserBo(DietTreatmentSystemUser dietTreatmentSystemUser) {
        this._DietTreatmentSystemUser = dietTreatmentSystemUser;
    }

    public DietTreatmentSystemUserBo(DietTreatmentSystemUser dietTreatmentSystemUser, SystemUserBo systemUserBo, SystemUserFunctionBo functionBo) {
       this(dietTreatmentSystemUser);
       this._SystemUser = systemUserBo;
       this._Function = functionBo;
    }
   
    public int getDietTreatmentSystemUserId() {
        return this._DietTreatmentSystemUser.getDietTreatmentSystemUserId();
    }
    
    public void setDietTreatmentSystemUserId(int dietTreatmentSystemUserId) {
        this._DietTreatmentSystemUser.setDietTreatmentSystemUserId(dietTreatmentSystemUserId);
    }
    public SystemUserBo getSystemUser() {
        return this._SystemUser;
    }
    
    public void setSystemUser(SystemUserBo systemUser) {
        this._SystemUser = systemUser;
    }
    public SystemUserFunctionBo getFunction() {
        return this._Function;
    }
    
    public void setFunction(SystemUserFunctionBo function) {
        this._Function = function;
    }




}


