package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1



/**
 * DietTreatmentSystemUser generated by hbm2java
 */
public class DietTreatmentSystemUser  implements java.io.Serializable {


     private int dietTreatmentSystemUserId;
     private SystemUser systemUser;
     private SystemUserFunction function;

    public DietTreatmentSystemUser() {
    }

    public DietTreatmentSystemUser(SystemUser systemUser, SystemUserFunction function) {
       this.systemUser = systemUser;
       this.function = function;
    }
   
    public int getDietTreatmentSystemUserId() {
        return this.dietTreatmentSystemUserId;
    }
    
    public void setDietTreatmentSystemUserId(int dietTreatmentSystemUserId) {
        this.dietTreatmentSystemUserId = dietTreatmentSystemUserId;
    }
    public SystemUser getSystemUser() {
        return this.systemUser;
    }
    
    public void setSystemUser(SystemUser systemUser) {
        this.systemUser = systemUser;
    }
    public SystemUserFunction getFunction() {
        return this.function;
    }
    
    public void setFunction(SystemUserFunction function) {
        this.function = function;
    }




}


