package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.DietTreatment;
import java.util.Date;
import java.util.Set;

/**
 * DietTreatmentBo generated by hbm2java
 */
public class DietTreatmentBo  implements java.io.Serializable {

     private TreatmentStateBo treatmentState;
     private DietTreatment _DietTreatment;

    public DietTreatmentBo() {
    }

    public DietTreatmentBo(DietTreatment dietTreatment){
        this._DietTreatment=dietTreatment;
    }
	
    public DietTreatmentBo(DietTreatment dietTreatment, Date start, int duration, String name, TreatmentStateBo treatmentStateBo) {
        this(dietTreatment);
        this._DietTreatment.setStart(start);
        this._DietTreatment.setDuration(duration);
        this._DietTreatment.setName(name);
        this._DietTreatment.setTreatmentState(treatmentStateBo.getTreatmentState());
    }
    public DietTreatmentBo(DietTreatment dietTreatment, Date start, int duration, String name, Set nutritionProtocols, Set dietPlans, Set dietParameters, Set patientStates, Set systemUsers, Set contactJournals, TreatmentStateBo treatmentStateBo) {
       this(dietTreatment, start, duration, name, treatmentStateBo);
       this._DietTreatment.setNutritionProtocols(nutritionProtocols);
       this._DietTreatment.setDietPlans(dietPlans);
       this._DietTreatment.setDietParameters(dietParameters);
       this._DietTreatment.setPatientStates(patientStates);
       this._DietTreatment.setSystemUsers(systemUsers);
       this._DietTreatment.setContactJournals(contactJournals);
    }
   
    public long getDietTreatmentId() {
        return this.getDietTreatment().getDietTreatmentId();
    }
    
    public void setDietTreatmentId(long dietTreatmentId) {
        this.getDietTreatment().setDietTreatmentId(dietTreatmentId);
    }
    public Date getStart() {
        return this.getDietTreatment().getStart();
    }
    
    public void setStart(Date start) {
        this.getDietTreatment().setStart(start);
    }
    public int getDuration() {
        return this.getDietTreatment().getDuration();
    }
    
    public void setDuration(int duration) {
        this.getDietTreatment().setDuration(duration);
    }
    public String getName() {
        return this.getDietTreatment().getName();
    }
    
    public void setName(String name) {
        this.getDietTreatment().setName(name);
    }
    public Set getNutritionProtocols() {
        return this.getDietTreatment().getNutritionProtocols();
    }
    
    public void setNutritionProtocols(Set nutritionProtocols) {
        this.getDietTreatment().setNutritionProtocols(nutritionProtocols);
    }
    public Set getDietPlans() {
        return this.getDietTreatment().getDietPlans();
    }
    
    public void setDietPlans(Set dietPlans) {
        this.getDietTreatment().setDietPlans(dietPlans);
    }
    public Set getDietParameters() {
        return this.getDietTreatment().getDietParameters();
    }
    
    public void setDietParameters(Set dietParameters) {
        this.getDietTreatment().setDietParameters(dietParameters);
    }
    public Set getPatientStates() {
        return this.getDietTreatment().getPatientStates();
    }
    
    public void setPatientStates(Set patientStates) {
        this.getDietTreatment().setPatientStates(patientStates);
    }
    public Set getSystemUsers() {
        return this.getDietTreatment().getSystemUsers();
    }
    
    public void setSystemUsers(Set systemUsers) {
        this.getDietTreatment().setSystemUsers(systemUsers);
    }
    public Set getContactJournals() {
        return this.getDietTreatment().getContactJournals();
    }
    
    public void setContactJournals(Set contactJournals) {
        this.getDietTreatment().setContactJournals(contactJournals);
    }
    public TreatmentStateBo getTreatmentState() {
        return this.treatmentState;
    }
    
    public void setTreatmentState(TreatmentStateBo treatmentState) {
        this.getDietTreatment().setTreatmentState(treatmentState.getTreatmentState());
        this.treatmentState = treatmentState;
    }

    /**
     * @return the _DietTreatment
     */
    protected DietTreatment getDietTreatment() {
        return _DietTreatment;
    }

    /**
     * @param DietTreatment the _DietTreatment to set
     */
    public void setDietTreatment(DietTreatment DietTreatment) {
        this._DietTreatment = DietTreatment;
    }




}


