package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.Gender;




/**
 * GenderBo generated by hbm2java
 */
public class GenderBo  implements java.io.Serializable, Saveable {

     private Gender _Gender;

    public GenderBo() {
    }

    public GenderBo(Gender gender) {
        this._Gender = gender;
    }

    public GenderBo(String name) {
       this(new Gender(name));
    }
   
    public String getName() {
        return this.getGender().getName();
    }
    
    public void setName(String name) {
        this.getGender().setName(name);
    }

    /**
     * @return the _Gender
     */
    protected Gender getGender() {
        return _Gender;
    }

    /**
     * @param Gender the _Gender to set
     */
    public void setGender(Gender Gender) {
        this._Gender = Gender;
    }

    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


