package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.Patient;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PatientBo generated by hbm2java
 */
public class PatientBo  implements java.io.Serializable {

     private GenderBo _GenderBo;

     private Patient _Patient;

    public PatientBo() {
    }

    public PatientBo(Patient patient){
        this._Patient=patient;
    }

	
    public PatientBo(Patient patient, String insuranceNumber, String forename, String lastname, String title, String street, String zip, String place, String country, Date birthday, GenderBo genderBo) {
        this();

        this._Patient.setInsuranceNumber(insuranceNumber);
        this._Patient.setForename(forename);
        this._Patient.setLastname(lastname);
        this._Patient.setTitle(title);
        this._Patient.setStreet(street);
        this._Patient.setZip(zip);
        this._Patient.setPlace(place);
        this._Patient.setCountry(country);
        this._Patient.setBirthday(birthday);
        this._Patient.setGender(genderBo.getGender());
    }
    public PatientBo(Patient patient, String insuranceNumber, String forename, String lastname, String title, String street, String zip, String place, String country, Date birthday, String job, String religion, String[] illnesses, String regime, Clob notice, GenderBo genderBo, Set familyanamnesis, Set patientstates, Set laborReports, Set treatments, Set disfavors) {
       this(patient, insuranceNumber, forename,lastname,title,street,zip,place,country,birthday,genderBo);
       this._Patient.setJob(job);
       this._Patient.setReligion(religion);
       this._Patient.setIllnesses(illnesses);
       this._Patient.setRegime(regime);
       this._Patient.setNotice(notice);
       this._Patient.setFamilyanamnesis(familyanamnesis);
       this._Patient.setPatientstate(patientstates);
       this._Patient.setLaborReports(laborReports);
       this._Patient.setTreatments(treatments);
       this._Patient.setDisfavors(disfavors);
    }
   
    public long getPatientId() {
        return this.getPatient().getPatientId();
    }
    
    public void setPatientId(long patientId) {
        this.getPatient().setPatientId(patientId);
    }
    public String getInsuranceNumber() {
        return this.getPatient().getInsuranceNumber();
    }
    
    public void setInsuranceNumber(String insuranceNumber) {
        this.getPatient().setInsuranceNumber(insuranceNumber);
    }
    public String getForename() {
        return this.getPatient().getForename();
    }
    
    public void setForename(String forename) {
        this.getPatient().setForename(forename);
    }
    public String getLastname() {
        return this.getPatient().getLastname();
    }
    
    public void setLastname(String lastname) {
        this.getPatient().setLastname(lastname);
    }
    public String getTitle() {
        return this.getPatient().getTitle();
    }
    
    public void setTitle(String title) {
        this.getPatient().setTitle(title);
    }
    public String getStreet() {
        return this.getPatient().getStreet();
    }
    
    public void setStreet(String street) {
        this.getPatient().setStreet(street);
    }
    public String getZip() {
        return this.getPatient().getZip();
    }
    
    public void setZip(String zip) {
        this.getPatient().setZip(zip);
    }
    public String getPlace() {
        return this.getPatient().getPlace();
    }
    
    public void setPlace(String place) {
        this.getPatient().setPlace(place);
    }
    public String getCountry() {
        return this.getPatient().getCountry();
    }
    
    public void setCountry(String country) {
        this.getPatient().setCountry(country);
    }
    public Date getBirthday() {
        return this.getPatient().getBirthday();
    }
    
    public void setBirthday(Date birthday) {
        this.getPatient().setBirthday(birthday);
    }
    public String getJob() {
        return this.getPatient().getJob();
    }
    
    public void setJob(String job) {
        this.getPatient().setJob(job);
    }
    public String getReligion() {
        return this.getPatient().getReligion();
    }
    
    public void setReligion(String religion) {
        this.getPatient().setReligion(religion);
    }
    public String[] getIllnesses() {
        return this.getPatient().getIllnesses();
    }
    
    public void setIllnesses(String[] illnesses) {
        this.getPatient().setIllnesses(illnesses);
    }
    public String getRegime() {
        return this.getPatient().getRegime();
    }
    
    public void setRegime(String regime) {
        this.getPatient().setRegime(regime);
    }
    public Clob getNotice() {
        return this.getPatient().getNotice();
    }
    
    public void setNotice(Clob notice) {
        this.getPatient().setNotice(notice);
    }
    public GenderBo getGender() {
        return this._GenderBo;
    }
    
    public void setGender(GenderBo gender) {
        this.getPatient().setGender(gender.getGender());
        this._GenderBo.setGender(getPatient().getGender());
    }
    public Set getFamilyanamnesis() {
        return this.getPatient().getFamilyanamnesis();
    }
    
    public void setFamilyanamnesis(Set familyanamnesis) {
        this.getPatient().setFamilyanamnesis(familyanamnesis);
    }
    public Set getPatientstate() {
        return this.getPatient().getPatientstate();
    }
    
    public void setPatientstate(Set patientstate) {
        this.getPatient().setPatientstate(patientstate);
    }
    public Set getLaborReports() {
        return this.getPatient().getLaborReports();
    }
    
    public void setLaborReports(Set laborReports) {
        this.getPatient().setLaborReports(laborReports);
    }
    public Set getTreatments() {
        return this.getPatient().getTreatments();
    }
    
    public void setTreatments(Set treatments) {
        this.getPatient().setTreatments(treatments);
    }
    public Set getDisfavors() {
        return this.getPatient().getDisfavors();
    }
    
    public void setDisfavors(Set disfavors) {
        this.getPatient().setDisfavors(disfavors);
    }

    /**
     * @return the _Patient
     */
    protected Patient getPatient() {
        return _Patient;
    }

    /**
     * @param Patient the _Patient to set
     */
    public void setPatient(Patient Patient) {
        this._Patient = Patient;
    }




}


