package at.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Meal generated by hbm2java
 */
public class Meal  implements java.io.Serializable {


     private long mealId;
     private String code;
     private String name;
     private Set dietParameters = new HashSet(0);
     private Set mealLines = new HashSet(0);

    public Meal() {
    }

	
    public Meal(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Meal(String code, String name, Set dietParameters, Set mealLines) {
       this.code = code;
       this.name = name;
       this.dietParameters = dietParameters;
       this.mealLines = mealLines;
    }
   
    public long getMealId() {
        return this.mealId;
    }
    
    public void setMealId(long mealId) {
        this.mealId = mealId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDietParameters() {
        return this.dietParameters;
    }
    
    public void setDietParameters(Set dietParameters) {
        this.dietParameters = dietParameters;
    }
    public Set getMealLines() {
        return this.mealLines;
    }
    
    public void setMealLines(Set mealLines) {
        this.mealLines = mealLines;
    }




}


