package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.Set;

import at.easydiet.model.DietParameter;
import at.easydiet.teamc.model.data.DietParameterData;



/**
 * DietParameter generated by hbm2java
 */
public class DietParameterBo extends DietParameterTemplateBo implements java.io.Serializable, Saveable,DietParameterData{


     private DietParameter _dietParameter;

    private DietParameterBo() {
    }

    public DietParameterBo(DietParameter dietparameter){
        this._dietParameter=dietparameter;
    }
	
    public DietParameterBo(CheckOperatorBo checkOperator, DietParameterTypeBo dietParameterType, ParameterDefinitionBo parameterDefinition) {
        this(new DietParameter(checkOperator.getCheckoperator(), dietParameterType.getDietParameterType(), parameterDefinition.getParameterDefinition()));
    }
    public DietParameterBo(CheckOperatorBo checkOperator, int duration, String value, DietParameterTypeBo dietParameterType, ParameterDefinitionBo parameterDefinition, Date start) {
        this(checkOperator, dietParameterType, parameterDefinition);
//        this._dieDietParameter.setDuration(duration);
//        this._dieDietParameter.setValue(value);
        this._dietParameter.setStart(start);
    }
   
    public Date getStart() {
        return getDietParameter().getStart();
    }
    
    public void setStart(Date start) {
        getDietParameter().setStart(start);
    }

    /**
     * @param dieDietParameter the _dietParameter to set
     */
    public void setDieDietParameter(DietParameter dieDietParameter) {
        this._dietParameter = dieDietParameter;
    }

    /**
     * @return the _dietParameter
     */
    protected DietParameter getDietParameter() {
        return _dietParameter;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

	@Override
	public String getParameterName() {
		return null;
	}

	@Override
	public String getParameterValue() {
		// TODO Auto-generated method stub
		return null;
	}
	



}


