package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import at.easydiet.model.FamilyAnamnesis;






/**
 * FamilyAnamnesisBo generated by hbm2java
 */
public class FamilyAnamnesisBo  implements java.io.Serializable, Saveable {

    private FamilyAnamnesis _FamilyAnamnesis;

    private FamilyAnamnesisBo() {
    }

    public FamilyAnamnesisBo(FamilyAnamnesis familyAnamnesis){
        this._FamilyAnamnesis=familyAnamnesis;
    }

    public FamilyAnamnesisBo(String person) {

        this(new FamilyAnamnesis(person));
    }

    public FamilyAnamnesisBo(String person, String[] illnesses) {
        this(person);
       this._FamilyAnamnesis.setIllnesses(illnesses);
    }
   
    public long getFamilyAnamnesisId() {
        return this.getFamilyAnamnesis().getFamilyAnamnesisId();
    }
    
    public void setFamilyAnamnesisId(long familyAnamnesisId) {
        this.getFamilyAnamnesis().setFamilyAnamnesisId(familyAnamnesisId);
    }
    public String getPerson() {
        return this.getFamilyAnamnesis().getPerson();
    }
    
    public void setPerson(String person) {
        this.getFamilyAnamnesis().setPerson(person);
    }
    public String[] getIllnesses() {
        return this.getFamilyAnamnesis().getIllnesses();
    }
    
    public void setIllnesses(String[] illnesses) {
        this.getFamilyAnamnesis().setIllnesses(illnesses);
    }

    /**
     * @return the _FamilyAnamnesis
     */
    protected FamilyAnamnesis getFamilyAnamnesis() {
        return _FamilyAnamnesis;
    }

    /**
     * @param FamilyAnamnesis the _FamilyAnamnesis to set
     */
    public void setFamilyAnamnesis(FamilyAnamnesis FamilyAnamnesis) {
        this._FamilyAnamnesis = FamilyAnamnesis;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


