package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.NutrimentParameter;
import at.easydiet.model.ParameterDefinitionUnit;




/**
 * NutrimentParameterBo generated by hbm2java
 */
public class NutrimentParameterBo  implements java.io.Serializable, Saveable {

     private ParameterDefinitionBo _parameterDefinition;

     private NutrimentParameter _NutrimentParameter;

    private NutrimentParameterBo() {
    }

    public NutrimentParameterBo(NutrimentParameter nutrimentParameter) {
        this._NutrimentParameter = nutrimentParameter;
    }

    public NutrimentParameterBo(String value, ParameterDefinitionBo parameterDefinitionBo, ParameterDefinitionUnit unit) {
       this(new NutrimentParameter(value, parameterDefinitionBo.getParameterDefinition()));
       
    }
   
    public long getNutrimentParameterId() {
        return this.getNutrimentParameter().getNutrimentParameterId();
    }
    
    public void setNutrimentParameterId(long nutrimentParameterId) {
        this.getNutrimentParameter().setNutrimentParameterId(nutrimentParameterId);
    }
    public String getValue() {
        return this.getNutrimentParameter().getValue();
    }
    
    public void setValue(String value) {
        this.getNutrimentParameter().setValue(value);
    }
    public ParameterDefinitionBo getParameterDefinition() {
        return this._parameterDefinition;
    }
    
    public void setParameterDefinition(ParameterDefinitionBo parameterDefinition) {
        this._NutrimentParameter.setParameterDefinition(parameterDefinition.getParameterDefinition());
        this._parameterDefinition = parameterDefinition;
    }

    /**
     * @return the _NutrimentParameter
     */
    protected NutrimentParameter getNutrimentParameter() {
        return _NutrimentParameter;
    }

    /**
     * @param NutrimentParameter the _NutrimentParameter to set
     */
    public void setNutrimentParameter(NutrimentParameter NutrimentParameter) {
        this._NutrimentParameter = NutrimentParameter;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


