package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.teamc.model.data.Saveable;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import at.easydiet.model.LaborReport;
import at.easydiet.model.PatientState;



/**
 * PatientStateBo generated by hbm2java
 */
public class PatientStateBo  implements java.io.Serializable, Saveable {

     private PatientStateTypeBo _type;
     private SystemUserBo _creator;

     private PatientState _PatientState;

    private PatientStateBo() {
    }

    public PatientStateBo(PatientState patientState){
        this._PatientState=patientState;
    }

	
    public PatientStateBo(Date date, PatientStateTypeBo typeBo, SystemUserBo creatorBo, PatientBo patientBo) {
        this(new PatientState(date, typeBo.getPatientStateType(), creatorBo.getSystemUser(), patientBo.getPatient()));
    }
    public PatientStateBo(Date date, Clob anamnesis, Integer weight, float weightPercentile, Integer height, float heightPercentile, int compliance, int motivation, PatientStateTypeBo typeBo, SystemUserBo creatorBo, Set<LaborReportBo> laborReportsBo, PatientBo patientBo) {
       this(date, typeBo, creatorBo, patientBo);
       this._PatientState.setAnamnesis(anamnesis);
       this._PatientState.setWeight(weight);
       this._PatientState.setWeightPercentile(weightPercentile);
       this._PatientState.setHeight(height);
       this._PatientState.setHeightPercentile(heightPercentile);
       this._PatientState.setCompliance(compliance);
       this._PatientState.setMotivation(motivation);
        for (LaborReportBo laborReportBo : laborReportsBo) {
            this._PatientState.getLaborReports().add(laborReportBo.getLaborReport());
        }
    }
   
    public long getPatientStateId() {
        return this._PatientState.getPatientStateId();
    }
    
    public void setPatientStateId(long patientStateId) {
        this._PatientState.setPatientStateId(patientStateId);
    }
    public Date getDate() {
        return this._PatientState.getDate();
    }
    
    public void setDate(Date date) {
        this._PatientState.setDate(date);
    }
    public Clob getAnamnesis() {
        return this._PatientState.getAnamnesis();
    }
    
    public void setAnamnesis(Clob anamnesis) {
        this._PatientState.setAnamnesis(anamnesis);
    }
    public Integer getWeight() {
        return this._PatientState.getWeight();
    }
    
    public void setWeight(Integer weight) {
        this._PatientState.setWeight(weight);
    }
    public float getWeightPercentile() {
        return this._PatientState.getWeightPercentile();
    }
    
    public void setWeightPercentile(float weightPercentile) {
        this._PatientState.setWeightPercentile(weightPercentile);
    }
    public Integer getHeight() {
        return this._PatientState.getHeight();
    }
    
    public void setHeight(Integer height) {
        this._PatientState.setHeight(height);
    }
    public float getHeightPercentile() {
        return this._PatientState.getHeightPercentile();
    }
    
    public void setHeightPercentile(float heightPercentile) {
        this._PatientState.setHeightPercentile(heightPercentile);
    }
    public int getCompliance() {
        return this._PatientState.getCompliance();
    }
    
    public void setCompliance(int compliance) {
        this._PatientState.setCompliance(compliance);
    }
    public int getMotivation() {
        return this._PatientState.getMotivation();
    }
    
    public void setMotivation(int motivation) {
        this._PatientState.setMotivation(motivation);
    }
    public PatientStateTypeBo getType() {
        return this._type;
    }
    
    public void setType(PatientStateTypeBo type) {
        this._PatientState.setType(type.getPatientStateType());
        this._type = type;
    }
    public SystemUserBo getCreator() {
        return this._creator;
    }
    
    public void setCreator(SystemUserBo creator) {
        this._PatientState.setCreator(creator.getSystemUser());
        this._creator = creator;
    }
    public Set<LaborReportBo> getLaborReports() {
        Set<LaborReportBo> temp = new HashSet<LaborReportBo>(this._PatientState.getLaborReports().size());
        for (LaborReport laborReport : this._PatientState.getLaborReports()) {
            temp.add(new LaborReportBo(laborReport));
        }
        return temp;
    }
    
    public void setLaborReports(Set<LaborReportBo> laborReportsBo) {
         for (LaborReportBo laborReportBo : laborReportsBo) {
            this._PatientState.getLaborReports().add(laborReportBo.getLaborReport());
        }
    }

    /**
     * @return the _PatientState
     */
    protected PatientState getPatientState() {
        return _PatientState;
    }

    /**
     * @param PatientState the _PatientState to set
     */
    public void setPatientState(PatientState PatientState) {
        this._PatientState = PatientState;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


