package at.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1



/**
 * DietParameterType generated by hbm2java
 */
public class DietParameterType  implements java.io.Serializable {


     private String name;

    public DietParameterType() {
    }

    public DietParameterType(String name) {
       this.name = name;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


