package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.CheckOperator;

/**
 * CheckOperator generated by hbm2java
 */
public class CheckOperatorBo  implements java.io.Serializable, Saveable {

    private CheckOperator _checkoperator;

    private CheckOperatorBo() {
    }

    public CheckOperatorBo(CheckOperator checkoperator) {
        this._checkoperator=checkoperator;
    }

    public CheckOperatorBo(String name) {
        this(new CheckOperator(name));
    }

    public void setCheckOperator(CheckOperator checkOperator){
        this.setCheckoperator(checkOperator);
    }
   
    public String getName() {
        return getCheckoperator().getName();
    }
    
    public void setName(String name) {
        getCheckoperator().setName(name);
    }

    /**
     * @return the _checkoperator
     */
    protected CheckOperator getCheckoperator() {
        return this._checkoperator;
    }

    /**
     * @param checkoperator the _checkoperator to set
     */
    public void setCheckoperator(CheckOperator checkoperator) {
        this._checkoperator = checkoperator;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


