package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import at.easydiet.model.DietParameter;
import at.easydiet.model.ParameterDefinitionUnit;
import at.easydiet.teamc.model.data.DietParameterData;

/**
 * DietParameter generated by hbm2java
 */
public class DietParameterBo extends DietParameterTemplateBo implements java.io.Serializable, Saveable, DietParameterData {

    private DietParameter _dietParameter;

    private DietParameterBo() {
    }

    /**
     *
     * @param dietparameter
     */
    public DietParameterBo(DietParameter dietparameter) {
        this._dietParameter = dietparameter;
        this.setDietParameterTemplate(dietparameter);
        this.setCheckOperatorBo(new CheckOperatorBo(_dietParameter.getCheckOperator()));
        this.setDietParameterType(new DietParameterTypeBo(_dietParameter.getDietParameterType()));
        this.setParameterDefinition(new ParameterDefinitionBo(_dietParameter.getParameterDefinition()));
        this.setStart(_dietParameter.getStart());
    }

    /**
     *
     * @param checkOperator
     * @param dietParameterType
     * @param parameterDefinition
     */
    public DietParameterBo(CheckOperatorBo checkOperator, DietParameterTypeBo dietParameterType, ParameterDefinitionBo parameterDefinition) {

        this(new DietParameter(checkOperator.getCheckoperator(),
                parameterDefinition.getUnit().toArray(new ParameterDefinitionUnitBo[parameterDefinition.getUnit().size()])[0].getParameterDefinitionUnit(),
                dietParameterType.getDietParameterType(),
                parameterDefinition.getParameterDefinition()));

    }

    /**
     *
     * @param checkOperator
     * @param duration
     * @param value
     * @param dietParameterType
     * @param parameterDefinition
     * @param start
     */
    public DietParameterBo(CheckOperatorBo checkOperator, int duration, String value, DietParameterTypeBo dietParameterType, ParameterDefinitionBo parameterDefinition, Date start) {
        this(checkOperator, dietParameterType, parameterDefinition);
//        this._dieDietParameter.setDuration(duration);
//        this._dieDietParameter.setValue(value);
        this._dietParameter.setStart(start);
    }

    /**
     *
     * @return
     */
    public Date getStart() {
        return getDietParameter().getStart();
    }

    /**
     *
     * @param start
     */
    public void setStart(Date start) {
        getDietParameter().setStart(start);
    }

    /**
     * @param dieDietParameter the _dietParameter to set
     */
    public void setDietParameter(DietParameter dieDietParameter) {
        this._dietParameter = dieDietParameter;
    }

    /**
     * @return the _dietParameter
     */
    protected DietParameter getDietParameter() {
        return _dietParameter;
    }

    /**
     *
     * @return
     */
    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     *
     * @return
     */
    @Override
    public String getParameterName() {
        return _dietParameter.getParameterDefinition().getName();

    }

    /**
     *
     * @return
     */
    @Override
    public String getParameterValue() {
        // TODO Auto-generated method stub
        return null;
    }
    
    public String toString(){
        return _dietParameter.getParameterDefinition().getName();
    }
}
