package at.easydiet.teamc.model;

// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.teamc.model.data.DietParameterData;
import at.easydiet.teamc.model.data.MealCodeData;
import at.easydiet.teamc.model.data.MealLineData;
import java.util.HashSet;
import java.util.Set;

import at.easydiet.model.DietParameter;
import at.easydiet.model.Meal;
import at.easydiet.model.MealLine;
import at.easydiet.teamc.model.data.MealData;

/**
 * MealBo generated by hbm2java
 */
public class MealCodeBo implements java.io.Serializable, Saveable, MealCodeData
{

    private Meal _Meal;

    private MealCodeBo()
    {}

    public MealCodeBo(Meal meal)
    {
        this._Meal = meal;
    }

    public MealCodeBo(String code, String name)
    {
        this(new Meal(code, name));
    }

    public MealCodeBo(String code, String name,
            Set<DietParameterBo> dietParameters, Set<MealLineBo> mealLines)
    {
        this(code, name);

        for (DietParameterBo dietParameterBo : dietParameters)
        {
            this._Meal.getDietParameters().add(
                    dietParameterBo.getDietParameter());
        }

        for (MealLineBo mealLineBo : mealLines)
        {
            this._Meal.getMealLines().add(mealLineBo.getMealLine());
        }
    }

    public String getCode()
    {
        return this.getMeal().getCode();
    }

    public void setCode(String code)
    {
        this.getMeal().setCode(code);
    }

    public String getName()
    {
        return this.getMeal().getName();
    }

    public void setName(String name)
    {
        this.getMeal().setName(name);
    }

    /**
     * @return the _Meal
     */
    protected Meal getMeal()
    {
        return _Meal;
    }

    /**
     * @param Meal
     *            the _Meal to set
     */
    public void setMeal(Meal Meal)
    {
        this._Meal = Meal;
    }

    @Override
    public boolean save()
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    /**
     * @see at.easydiet.teamc.model.data.MealCodeData#getMealName()
     */
    @Override
    public String getMealName()
    {
        return null;
    }

    /**
     * @see at.easydiet.teamc.model.data.MealCodeData#getMealCode()
     */
    @Override
    public String getMealCode()
    {
        return null;
    }

}
