package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import at.easydiet.model.DietParameter;
import at.easydiet.model.Meal;
import at.easydiet.model.MealLine;



/**
 * MealBo generated by hbm2java
 */
public class MealBo  implements java.io.Serializable, Saveable {

     private  Meal _Meal;

    private MealBo() {
    }

    public MealBo(Meal meal){
        this._Meal = meal;
    }

    public MealBo(String code, String name) {
        this(new Meal(code, name));
    }
    public MealBo(String code, String name, Set<DietParameterBo> dietParameters, Set<MealLineBo> mealLines) {
       this(code, name);

        for (DietParameterBo dietParameterBo : dietParameters) {
            this._Meal.getDietParameters().add(dietParameterBo.getDietParameter());
        }

        for (MealLineBo mealLineBo : mealLines) {
            this._Meal.getMealLines().add(mealLineBo.getMealLine());
        }
       
    }
   
    public long getMealId() {
        return this.getMeal().getMealId();
    }
    
    public void setMealId(long mealId) {
        this.getMeal().setMealId(mealId);
    }
    public String getCode() {
        return this.getMeal().getCode();
    }
    
    public void setCode(String code) {
        this.getMeal().setCode(code);
    }
    public String getName() {
        return this.getMeal().getName();
    }
    
    public void setName(String name) {
        this.getMeal().setName(name);
    }
    public Set<DietParameterBo> getDietParameters() {
        Set<DietParameterBo> temp = new HashSet<DietParameterBo>(this._Meal.getDietParameters().size());
        for (DietParameter dietParameter : this._Meal.getDietParameters()) {
            temp.add(new DietParameterBo(dietParameter));
        }
        return temp;
    }
    
    public void setDietParameters(Set<DietParameterBo> dietParametersBo) {
        for (DietParameterBo dietParameterBo : dietParametersBo) {
            this._Meal.getDietParameters().add(dietParameterBo.getDietParameter());
        }
    }
    public Set<MealLineBo> getMealLines() {
        Set<MealLineBo> temp = new HashSet<MealLineBo>(this._Meal.getMealLines().size());
        for (MealLine mealLine : this._Meal.getMealLines()) {
            temp.add(new MealLineBo(mealLine));
        }
        return temp;
    }
    
    public void setMealLines(Set<MealLineBo> mealLinesBo) {
        for (MealLineBo mealLineBo : mealLinesBo) {
            this._Meal.getMealLines().add(mealLineBo.getMealLine());
        }
    }

    /**
     * @return the _Meal
     */
    protected Meal getMeal() {
        return _Meal;
    }

    /**
     * @param Meal the _Meal to set
     */
    public void setMeal(Meal Meal) {
        this._Meal = Meal;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


