package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.NutrimentParameter;
import at.easydiet.model.ParameterDefinitionUnit;
import at.easydiet.teamc.exception.ParameterWithoutUnitException;
import at.easydiet.teamc.model.data.NutrimentParameterData;
import at.easydiet.teamc.model.data.ParameterDefinitionUnitData;




/**
 * NutrimentParameterBo generated by hbm2java
 */
public class NutrimentParameterBo  implements java.io.Serializable, Saveable, NutrimentParameterData {

     private ParameterDefinitionBo _parameterDefinition;

     private NutrimentParameter _NutrimentParameter;

    private NutrimentParameterBo() {
    }

    public NutrimentParameterBo(NutrimentParameter nutrimentParameter) {
        this._NutrimentParameter = nutrimentParameter;
        this._parameterDefinition = new ParameterDefinitionBo(nutrimentParameter.getParameterDefinition());
    }

    public NutrimentParameterBo(String value, ParameterDefinitionBo parameterDefinitionBo, ParameterDefinitionUnitBo unit) {
        NutrimentParameter temp;
        if(unit==null){
            temp=new NutrimentParameter(value, parameterDefinitionBo.getParameterDefinition(),null);
        }else{
            temp=new NutrimentParameter(value, parameterDefinitionBo.getParameterDefinition(),unit.getParameterDefinitionUnit());
        }
        this._NutrimentParameter=temp;
        this._parameterDefinition=parameterDefinitionBo;
       
    }
   
    public long getNutrimentParameterId() {
        return this.getNutrimentParameter().getNutrimentParameterId();
    }
    
    public void setNutrimentParameterId(long nutrimentParameterId) {
        this.getNutrimentParameter().setNutrimentParameterId(nutrimentParameterId);
    }
    public String getValue() {
        return this.getNutrimentParameter().getValue();
    }

    public float getAmount() {
        return Float.parseFloat(this.getValue());
    }
    
    public void setValue(String value) {
        this.getNutrimentParameter().setValue(value);
    }
    public ParameterDefinitionBo getParameterDefinition() {
        return this._parameterDefinition;
    }
    
    public void setParameterDefinition(ParameterDefinitionBo parameterDefinition) {
        this._NutrimentParameter.setParameterDefinition(parameterDefinition.getParameterDefinition());
        this._parameterDefinition = parameterDefinition;
    }

    /**
     * @return the _NutrimentParameter
     */
    protected NutrimentParameter getNutrimentParameter() {
        return _NutrimentParameter;
    }

    /**
     * @param NutrimentParameter the _NutrimentParameter to set
     */
    public void setNutrimentParameter(NutrimentParameter NutrimentParameter) {
        this._NutrimentParameter = NutrimentParameter;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String getName() {
        return this._parameterDefinition.getName();
    }

    public ParameterDefinitionUnitData getUnit() throws ParameterWithoutUnitException{
        return this._parameterDefinition.getUnitData();
    }




}


