package at.easydiet.teamc.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.teamc.model.data.Saveable;
import at.easydiet.model.ParameterDefinitionDataType;




/**
 * ParameterDefinitionDataTypeBo generated by hbm2java
 */
public class ParameterDefinitionDataTypeBo  implements java.io.Serializable, Saveable {



     private ParameterDefinitionDataType _ParameterDefinitionDataType;

    private ParameterDefinitionDataTypeBo() {
    }

    public ParameterDefinitionDataTypeBo(ParameterDefinitionDataType parameterDefinitionDataType) {
        this._ParameterDefinitionDataType=parameterDefinitionDataType;
    }

    public ParameterDefinitionDataTypeBo(String name) {
        this(new ParameterDefinitionDataType(name));
    }
   
    public String getName() {
        return this.getParameterDefinitionDataType().getName();
    }
    
    public void setName(String name) {
        this.getParameterDefinitionDataType().setName(name);
    }

    /**
     * @param ParameterDefinitionDataType the _ParameterDefinitionDataType to set
     */
    public void setParameterDefinitionDataType(ParameterDefinitionDataType ParameterDefinitionDataType) {
        this._ParameterDefinitionDataType = ParameterDefinitionDataType;
    }

    /**
     * @return the _ParameterDefinitionDataType
     */
    protected ParameterDefinitionDataType getParameterDefinitionDataType() {
        return _ParameterDefinitionDataType;
    }

    @Override
    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


