package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1



/**
 * ContactType generated by hbm2java
 */
public class ContactType  implements java.io.Serializable {


     private String name;

    public ContactType() {
    }

    public ContactType(String name) {
       this.name = name;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


