package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import java.sql.Clob;
import java.util.Date;
import at.easydiet.model.ContactJournal;
import at.easydiet.model.ContactType;
import at.easydiet.model.SystemUser;

/**
 * ContactJournal generated by hbm2java
 */
public class ContactJournalBo  implements java.io.Serializable {


     private ContactJournal _contactjournal;

    public ContactJournalBo() {
    }

    public ContactJournalBo(ContactJournal contactjournal){
        this._contactjournal=contactjournal;
    }

	
    public ContactJournalBo(ContactJournal contactjournal, Date date, SystemUser createdBy, ContactType contactType) {
        this(contactjournal);
        setDate(date);
        setCreatedBy(createdBy);
        setContactType(contactType);
    }
    public ContactJournalBo(ContactJournal contactjournal, Date date, Clob description, SystemUser createdBy, ContactType contactType) {
        this(contactjournal);
        setDate(date);
        setDescription(description);
        setCreatedBy(createdBy);
        setContactType(contactType);
    }
   
    public long getContactJournalId() {
        return getContactjournal().getContactJournalId();
    }
    
    public void setContactJournalId(long contactJournalId) {
        getContactjournal().setContactJournalId(contactJournalId);
    }
    public Date getDate() {
        return getContactjournal().getDate();

    }
    
    public void setDate(Date date) {
        getContactjournal().setDate(date);
    }
    public Clob getDescription() {
        return getContactjournal().getDescription();
    }
    
    public void setDescription(Clob description) {
        getContactjournal().setDescription(description);
    }
    public SystemUser getCreatedBy() {
        return getContactjournal().getCreatedBy();
    }
    
    public void setCreatedBy(SystemUser createdBy) {
        getContactjournal().setCreatedBy(createdBy);
    }
    public ContactType getContactType() {
        return getContactjournal().getContactType();
    }
    
    public void setContactType(ContactType contactType) {
        getContactjournal().setContactType(contactType);
    }

    /**
     * @param contactjournal the _contactjournal to set
     */
    public void setContactjournal(ContactJournal contactjournal) {
        this._contactjournal = contactjournal;
    }

    /**
     * @return the _contactjournal
     */
    protected ContactJournal getContactjournal() {
        return _contactjournal;
    }




}


