package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import java.sql.Clob;
import java.util.Date;
import at.easydiet.model.ContactJournal;
import at.easydiet.model.ContactType;
import at.easydiet.model.SystemUser;

/**
 * ContactJournal generated by hbm2java
 */
public class ContactJournalBo  implements java.io.Serializable {


     private ContactJournal _contactjournal;

    public ContactJournalBo() {
    }

    public ContactJournalBo(ContactJournal contactjournal){
        setContactjournal(contactjournal);
    }

	
    public ContactJournalBo(ContactJournal contactjournal, Date date, SystemUser createdBy, ContactType contactType) {
        this(contactjournal);
        setDate(date);
        setCreatedBy(createdBy);
        setContactType(contactType);
    }
    public ContactJournalBo(ContactJournal contactjournal, Date date, Clob description, SystemUser createdBy, ContactType contactType) {
        this(contactjournal);
        setDate(date);
        setDescription(description);
        setCreatedBy(createdBy);
        setContactType(contactType);
    }
   
    public long getContactJournalId() {
        return _contactjournal.getContactJournalId();
    }
    
    public void setContactJournalId(long contactJournalId) {
        _contactjournal.setContactJournalId(contactJournalId);
    }
    public Date getDate() {
        return _contactjournal.getDate();

    }
    
    public void setDate(Date date) {
        _contactjournal.setDate(date);
    }
    public Clob getDescription() {
        return _contactjournal.getDescription();
    }
    
    public void setDescription(Clob description) {
        _contactjournal.setDescription(description);
    }
    public SystemUser getCreatedBy() {
        return _contactjournal.getCreatedBy();
    }
    
    public void setCreatedBy(SystemUser createdBy) {
        _contactjournal.setCreatedBy(createdBy);
    }
    public ContactType getContactType() {
        return _contactjournal.getContactType();
    }
    
    public void setContactType(ContactType contactType) {
        _contactjournal.setContactType(contactType);
    }

    /**
     * @param contactjournal the _contactjournal to set
     */
    public void setContactjournal(ContactJournal contactjournal) {
        this._contactjournal = contactjournal;
    }




}


