package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.ContactType;



/**
 * ContactType generated by hbm2java
 */
public class ContactTypeBo  implements java.io.Serializable {


    private ContactType _contactType;

    public ContactTypeBo() {
    }

    public ContactTypeBo(ContactType contactType){
        this._contactType=contactType;
    }

    public ContactTypeBo(String name, ContactType contactType) {
        this(contactType);
       setName(name);
    }
   
    public String getName() {
        return getContactType().getName();
    }
    
    public void setName(String name) {
        getContactType().setName(name);
    }

    /**
     * @param contactType the _contactType to set
     */
    public void setContactType(ContactType contactType) {
        setContactType(contactType);
    }

    /**
     * @return the _contactType
     */
    protected  ContactType getContactType() {
        return _contactType;
    }

}


