package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.DietParameterTemplate;




/**
 * DietParameterTemplate generated by hbm2java
 */
public class DietParameterTemplateBo  implements java.io.Serializable {

    private DietParameterTemplate _dietParameterTemplate;
     private long dietParameterTemplateId;
     private CheckOperatorBo _checkOperatorBo;
     private int duration;
     private String value;
     private DietParameterType dietParameterType;
     private ParameterDefinition parameterDefinition;

    public DietParameterTemplateBo() {
    }

    public DietParameterTemplateBo(DietParameterTemplate dietParameterTemplate){
        setDietParameterTemplate(dietParameterTemplate);
    }

	
    public DietParameterTemplateBo(CheckOperatorBo checkOperatorBo, DietParameterType dietParameterType, ParameterDefinition parameterDefinition) {
        setCheckOperator(checkOperatorBo);
        this.dietParameterType = dietParameterType;
        this.parameterDefinition = parameterDefinition;
    }
    public DietParameterTemplateBo(CheckOperatorBo checkOperator, int duration, String value, DietParameterType dietParameterType, ParameterDefinition parameterDefinition) {
       this._checkOperatorBo = checkOperator;
       this.duration = duration;
       this.value = value;
       this.dietParameterType = dietParameterType;
       this.parameterDefinition = parameterDefinition;
    }
   
    public long getDietParameterTemplateId() {
        return this.dietParameterTemplateId;
    }
    
    public void setDietParameterTemplateId(long dietParameterTemplateId) {
        this.dietParameterTemplateId = dietParameterTemplateId;
    }
    public CheckOperatorBo getCheckOperatorBo() {
        return this._checkOperatorBo;
    }
    
    public void setCheckOperator(CheckOperatorBo checkOperator) {
        this._checkOperatorBo = checkOperator;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public DietParameterType getDietParameterType() {
        return this.dietParameterType;
    }
    
    public void setDietParameterType(DietParameterType dietParameterType) {
        this.dietParameterType = dietParameterType;
    }
    public ParameterDefinition getParameterDefinition() {
        return this.parameterDefinition;
    }
    
    public void setParameterDefinition(ParameterDefinition parameterDefinition) {
        this.parameterDefinition = parameterDefinition;
    }

    /**
     * @param dietParameterTemplate the _dietParameterTemplate to set
     */
    public void setDietParameterTemplate(DietParameterTemplate dietParameterTemplate) {
        this._dietParameterTemplate = dietParameterTemplate;
    }




}


