package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.DietParameterTemplate;




/**
 * DietParameterTemplate generated by hbm2java
 */
public class DietParameterTemplateBo  implements java.io.Serializable {

    private DietParameterTemplate _dietParameterTemplate;
     private CheckOperatorBo _checkOperatorBo;
     private DietParameterTypeBo _dietParameterTypeBo;
     private ParameterDefinitionBo _parameterDefinitionBo;

    public DietParameterTemplateBo() {
    }

    public DietParameterTemplateBo(DietParameterTemplate dietParameterTemplate){
        this._dietParameterTemplate=dietParameterTemplate;
    }

	
    public DietParameterTemplateBo(CheckOperatorBo checkOperatorBo, DietParameterTypeBo dietParameterType, ParameterDefinitionBo parameterDefinition) {
        this._checkOperatorBo=checkOperatorBo;
        this._dietParameterTypeBo = dietParameterType;
        this._parameterDefinitionBo = parameterDefinition;
    }
    public DietParameterTemplateBo(CheckOperatorBo checkOperator, int duration, String value, DietParameterTypeBo dietParameterType, ParameterDefinitionBo parameterDefinition) {
       this(checkOperator, dietParameterType, parameterDefinition);
       _dietParameterTemplate.setDuration(duration);
       _dietParameterTemplate.setValue(value);
    }
   
    public long getDietParameterTemplateId() {
        return _dietParameterTemplate.getDietParameterTemplateId();
    }
    
    public void setDietParameterTemplateId(long dietParameterTemplateId) {
        this._dietParameterTemplate.setDietParameterTemplateId(dietParameterTemplateId);
    }
    public CheckOperatorBo getCheckOperatorBo() {
        return this._checkOperatorBo;
    }
    
    public void setCheckOperatorBo(CheckOperatorBo checkOperator) {
        this._checkOperatorBo = checkOperator;
    }
    public int getDuration() {
        return _dietParameterTemplate.getDuration();
    }
    
    public void setDuration(int duration) {
        this._dietParameterTemplate.setDuration(duration);
    }
    public String getValue() {
        return _dietParameterTemplate.getValue();
    }
    
    public void setValue(String value) {
        this._dietParameterTemplate.setValue(value);
    }
    public DietParameterTypeBo getDietParameterType() {
        return this._dietParameterTypeBo;
    }
    
    public void setDietParameterType(DietParameterTypeBo dietParameterType) {
        this._dietParameterTypeBo = dietParameterType;
    }
    public ParameterDefinitionBo getParameterDefinition() {
        return this._parameterDefinitionBo;
    }
    
    public void setParameterDefinition(ParameterDefinitionBo parameterDefinition) {
        this._parameterDefinitionBo = parameterDefinition;
    }

    /**
     * @param dietParameterTemplate the _dietParameterTemplate to set
     */
    public void setDietParameterTemplate(DietParameterTemplate dietParameterTemplate) {
        this._dietParameterTemplate = dietParameterTemplate;
    }




}


