package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.DietParameterType;




/**
 * DietParameterTypeBo generated by hbm2java
 */
public class DietParameterTypeBo  implements java.io.Serializable {


     private DietParameterType _DietParameterType;

    public DietParameterTypeBo() {
    }

     public DietParameterTypeBo(DietParameterType dietParameterType) {
    }

    public DietParameterTypeBo(DietParameterType dietParameterType, String name) {
        this(dietParameterType);
       setName(name);
    }
   
    public String getName() {
        return getDietParameterType().getName();
    }
    
    public void setName(String name) {
        getDietParameterType().setName(name);
    }

    /**
     * @param DietParameter the _DietParameter to set
     */
    public void setDietParameterType(DietParameterType dietParameterType) {
        this._DietParameterType = dietParameterType;
    }

    /**
     * @return the _DietParameterType
     */
    protected DietParameterType getDietParameterType() {
        return _DietParameterType;
    }




}


