package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * DietParameterSet generated by hbm2java
 */
public class DietParameterSet  implements java.io.Serializable {


     private long dietParameterSetId;
     private String name;
     private Set dietParameterTemplates = new HashSet(0);

    public DietParameterSet() {
    }

	
    public DietParameterSet(String name) {
        this.name = name;
    }
    public DietParameterSet(String name, Set dietParameterTemplates) {
       this.name = name;
       this.dietParameterTemplates = dietParameterTemplates;
    }
   
    public long getDietParameterSetId() {
        return this.dietParameterSetId;
    }
    
    public void setDietParameterSetId(long dietParameterSetId) {
        this.dietParameterSetId = dietParameterSetId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDietParameterTemplates() {
        return this.dietParameterTemplates;
    }
    
    public void setDietParameterTemplates(Set dietParameterTemplates) {
        this.dietParameterTemplates = dietParameterTemplates;
    }




}


