package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.LaborReport;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LaborReportBo generated by hbm2java
 */
public class LaborReportBo  implements java.io.Serializable {

     private SystemUserBo _creator;

     private LaborReport _LaborReport;

    public LaborReportBo() {
    }

    public LaborReportBo(LaborReport laborReport){
        this._LaborReport = laborReport;
    }

	

    public LaborReportBo(LaborReport laborReport, Date date, SystemUserBo creatorBo) {
        this(laborReport);
        this._LaborReport.setDate(date);
        this._LaborReport.setCreator(creatorBo.getSystemUser());
    }
    public LaborReportBo(LaborReport laborReport, Date date, Clob notice, SystemUserBo creatorBo, Set dietParameters) {
       this(laborReport, date, creatorBo);
       this._LaborReport.setNotice(notice);
       this._LaborReport.setDietParameters(dietParameters);
    }
   
    public long getLaborReportId() {
        return this.getLaborReport().getLaborReportId();
    }
    
    public void setLaborReportId(long laborReportId) {
        this.getLaborReport().setLaborReportId(laborReportId);
    }
    public Date getDate() {
        return this.getLaborReport().getDate();
    }
    
    public void setDate(Date date) {
        this.getLaborReport().setDate(date);
    }
    public Clob getNotice() {
        return this.getLaborReport().getNotice();
    }
    
    public void setNotice(Clob notice) {
        this.getLaborReport().setNotice(notice);
    }
    public SystemUserBo getCreator() {
        return this._creator;
    }
    
    public void setCreator(SystemUserBo creatorBo) {
        this.getLaborReport().setCreator(creatorBo.getSystemUser());
        this._creator = creatorBo;
    }
    public Set getDietParameters() {
        return this.getLaborReport().getDietParameters();
    }
    
    public void setDietParameters(Set dietParameters) {
        this.getLaborReport().setDietParameters(dietParameters);
    }

    /**
     * @return the _LaborReport
     */
    protected LaborReport getLaborReport() {
        return _LaborReport;
    }

    /**
     * @param LaborReport the _LaborReport to set
     */
    public void setLaborReport(LaborReport LaborReport) {
        this._LaborReport = LaborReport;
    }




}


