package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.DietPlan;
import at.easydiet.model.NutritionProtocol;
import java.sql.Clob;
import java.util.Date;
import java.util.Set;

/**
 * NutritionProtocolBo generated by hbm2java
 */
public class NutritionProtocolBo extends at.fhv.teamc.easydiet.model.DietPlanBo implements java.io.Serializable, Saveable {


     private NutritionProtocol _NutritionProtocol;

    private NutritionProtocolBo() {
    }

    public NutritionProtocolBo(NutritionProtocol nutritionProtocol){
        this._NutritionProtocol=nutritionProtocol;
    }

	
    public NutritionProtocolBo(DietPlan dietPlan, String name, Date createdOn, PlanTypeBo planTypeBo, SystemUserBo creatorBo, Date date) {
        this(new NutritionProtocol(name, createdOn, planTypeBo.getPlanType(), creatorBo.getSystemUser(), date));
    }
    public NutritionProtocolBo(DietPlan dietPlan, String name, Date createdOn, PlanTypeBo planType, Set<DietParameterBo> dietParametersBo, SystemUserBo creatorBo, Set<TimeSpanBo> timeSpansBo, Date date, String contact, Clob notice) {
       this(dietPlan, name, createdOn, planType, creatorBo, date);

       for (DietParameterBo dietParameterBo : dietParametersBo) {
            this._NutritionProtocol.getDietParameters().add(dietParameterBo.getDieDietParameter());
        }

       for (TimeSpanBo timeSpanBo : timeSpansBo) {
            this._NutritionProtocol.getTimeSpans().add(timeSpanBo.getTimeSpan());
        }
       this._NutritionProtocol.setContact(contact);
       this._NutritionProtocol.setNotice(notice);
    }
   
    public Date getDate() {
        return this.getNutritionProtocol().getDate();
    }
    
    public void setDate(Date date) {
        this.getNutritionProtocol().setDate(date);
    }
    public String getContact() {
        return this.getNutritionProtocol().getContact();
    }
    
    public void setContact(String contact) {
        this.getNutritionProtocol().setContact(contact);
    }
    public Clob getNotice() {
        return this.getNutritionProtocol().getNotice();
    }
    
    public void setNotice(Clob notice) {
        this.getNutritionProtocol().setNotice(notice);
    }

    /**
     * @return the _NutritionProtocol
     */
    protected NutritionProtocol getNutritionProtocol() {
        return _NutritionProtocol;
    }

    /**
     * @param NutritionProtocol the _NutritionProtocol to set
     */
    public void setNutritionProtocol(NutritionProtocol NutritionProtocol) {
        this._NutritionProtocol = NutritionProtocol;
    }

    public boolean save() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


