package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.NutrimentParameter;




/**
 * NutrimentParameterBo generated by hbm2java
 */
public class NutrimentParameterBo  implements java.io.Serializable {

     private ParameterDefinitionBo _parameterDefinition;

     private NutrimentParameter _NutrimentParameter;

    public NutrimentParameterBo() {
    }

    public NutrimentParameterBo(NutrimentParameter nutrimentParameter) {
        this._NutrimentParameter = nutrimentParameter;
    }

    public NutrimentParameterBo(NutrimentParameter nutrimentParameter, String value, ParameterDefinitionBo parameterDefinition) {
       this(nutrimentParameter);
        this._NutrimentParameter.setValue(value);
       this._NutrimentParameter.setParameterDefinition(parameterDefinition.getParameterDefinition());
    }
   
    public long getNutrimentParameterId() {
        return this.getNutrimentParameter().getNutrimentParameterId();
    }
    
    public void setNutrimentParameterId(long nutrimentParameterId) {
        this.getNutrimentParameter().setNutrimentParameterId(nutrimentParameterId);
    }
    public String getValue() {
        return this.getNutrimentParameter().getValue();
    }
    
    public void setValue(String value) {
        this.getNutrimentParameter().setValue(value);
    }
    public ParameterDefinitionBo getParameterDefinition() {
        return this._parameterDefinition;
    }
    
    public void setParameterDefinition(ParameterDefinitionBo parameterDefinition) {
        this._NutrimentParameter.setParameterDefinition(parameterDefinition.getParameterDefinition());
        this._parameterDefinition = parameterDefinition;
    }

    /**
     * @return the _NutrimentParameter
     */
    protected NutrimentParameter getNutrimentParameter() {
        return _NutrimentParameter;
    }

    /**
     * @param NutrimentParameter the _NutrimentParameter to set
     */
    public void setNutrimentParameter(NutrimentParameter NutrimentParameter) {
        this._NutrimentParameter = NutrimentParameter;
    }




}


