package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1



/**
 * NutrimentParameter generated by hbm2java
 */
public class NutrimentParameter  implements java.io.Serializable {


     private long nutrimentParameterId;
     private String value;
     private ParameterDefinitionBo parameterDefinition;

    public NutrimentParameter() {
    }

    public NutrimentParameter(String value, ParameterDefinitionBo parameterDefinition) {
       this.value = value;
       this.parameterDefinition = parameterDefinition;
    }
   
    public long getNutrimentParameterId() {
        return this.nutrimentParameterId;
    }
    
    public void setNutrimentParameterId(long nutrimentParameterId) {
        this.nutrimentParameterId = nutrimentParameterId;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public ParameterDefinitionBo getParameterDefinition() {
        return this.parameterDefinition;
    }
    
    public void setParameterDefinition(ParameterDefinitionBo parameterDefinition) {
        this.parameterDefinition = parameterDefinition;
    }




}


