package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.ParameterDefinitionDataType;




/**
 * ParameterDefinitionDataTypeBo generated by hbm2java
 */
public class ParameterDefinitionDataTypeBo  implements java.io.Serializable {



     private ParameterDefinitionDataType _ParameterDefinitionDataType;

    public ParameterDefinitionDataTypeBo() {
    }

    public ParameterDefinitionDataTypeBo(ParameterDefinitionDataType parameterDefinitionDataType) {
        this._ParameterDefinitionDataType=parameterDefinitionDataType;
    }

    public ParameterDefinitionDataTypeBo(ParameterDefinitionDataType parameterDefinitionDataType, String name) {
        this(parameterDefinitionDataType);
        this._ParameterDefinitionDataType.setName(name);
    }
   
    public String getName() {
        return this._ParameterDefinitionDataType.getName();
    }
    
    public void setName(String name) {
        this._ParameterDefinitionDataType.setName(name);
    }

    /**
     * @param ParameterDefinitionDataType the _ParameterDefinitionDataType to set
     */
    public void setParameterDefinitionDataType(ParameterDefinitionDataType ParameterDefinitionDataType) {
        this._ParameterDefinitionDataType = ParameterDefinitionDataType;
    }




}


