package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.PatientStateType;




/**
 * PatientStateTypeBo generated by hbm2java
 */
public class PatientStateTypeBo  implements java.io.Serializable {


     private String name;
     private PatientStateType _PatientStateType;

    public PatientStateTypeBo() {
    }

    public PatientStateTypeBo(String name) {
       this.name = name;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the _PatientStateType
     */
    public PatientStateType getPatientStateType() {
        return _PatientStateType;
    }

    /**
     * @param PatientStateType the _PatientStateType to set
     */
    public void setPatientStateType(PatientStateType PatientStateType) {
        this._PatientStateType = PatientStateType;
    }




}


