package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1


import at.easydiet.model.TimeSpan;
import java.util.Date;
import java.util.Set;

/**
 * TimeSpanBo generated by hbm2java
 */
public class TimeSpanBo  implements java.io.Serializable {

     private TimeSpan _TimeSpan;

    public TimeSpanBo() {
    }

    public TimeSpanBo(TimeSpan timeSpan){
        this._TimeSpan=timeSpan;
    }

	
    public TimeSpanBo(TimeSpan timeSpan, Date start, int duration) {
        this(timeSpan);
        this._TimeSpan.setStart(start);
        this._TimeSpan.setDuration(duration);
    }
    public TimeSpanBo(TimeSpan timeSpan, Date start, int duration, Set dietParameters, Set meals) {
       this(timeSpan, start, duration);
       this._TimeSpan.setDietParameters(dietParameters);
       this._TimeSpan.setMeals(meals);
    }
   
    public long getTimeSpanId() {
        return this.getTimeSpan().getTimeSpanId();
    }
    
    public void setTimeSpanId(long timeSpanId) {
        this.getTimeSpan().setTimeSpanId(timeSpanId);
    }
    public Date getStart() {
        return this.getTimeSpan().getStart();
    }
    
    public void setStart(Date start) {
        this.getTimeSpan().setStart(start);
    }
    public int getDuration() {
        return this.getTimeSpan().getDuration();
    }
    
    public void setDuration(int duration) {
        this.getTimeSpan().setDuration(duration);
    }
    public Set getDietParameters() {
        return this.getTimeSpan().getDietParameters();
    }
    
    public void setDietParameters(Set dietParameters) {
        this.getTimeSpan().setDietParameters(dietParameters);
    }
    public Set getMeals() {
        return this.getTimeSpan().getMeals();
    }
    
    public void setMeals(Set meals) {
        this.getTimeSpan().setMeals(meals);
    }

    /**
     * @return the _TimeSpan
     */
    protected TimeSpan getTimeSpan() {
        return _TimeSpan;
    }

    /**
     * @param TimeSpan the _TimeSpan to set
     */
    public void setTimeSpan(TimeSpan TimeSpan) {
        this._TimeSpan = TimeSpan;
    }




}


