package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.TreatmentState;

/**
 * TreatmentStateBo generated by hbm2java
 */
public class TreatmentStateBo  implements java.io.Serializable {


    private TreatmentState _TreatmentState;

    public TreatmentStateBo() {
    }

    public TreatmentStateBo(TreatmentState treatmentState)
    {
        this._TreatmentState = treatmentState;
    }

    public TreatmentStateBo(TreatmentState treatmentState, String name) {
       this(treatmentState);
       this._TreatmentState.setName(name);
    }
   
    public String getName() {
        return this.getTreatmentState().getName();
    }
    
    public void setName(String name) {
        this.getTreatmentState().setName(name);
    }

    /**
     * @return the _TreatmentState
     */
    public TreatmentState getTreatmentState() {
        return _TreatmentState;
    }

    /**
     * @param TreatmentState the _TreatmentState to set
     */
    public void setTreatmentState(TreatmentState TreatmentState) {
        this._TreatmentState = TreatmentState;
    }




}


