package at.fhv.teamc.easydiet.model;
// Generated 02.04.2011 00:41:04 by Hibernate Tools 3.4.0.CR1

import at.easydiet.model.UserRight;




/**
 * UserRightBo generated by hbm2java
 */
public class UserRightBo  implements java.io.Serializable {


     private String name;

     private UserRight _UserRight;

    public UserRightBo() {
    }

    public UserRightBo(UserRight userRight){
        this._UserRight=userRight;
    }

    public UserRightBo(UserRight userRight, String name) {
        this(userRight);
       this._UserRight.setName(name);
    }
   
    public String getName() {
        return this.getUserRight().getName();
    }
    
    public void setName(String name) {
        this.getUserRight().setName(name);
    }

    /**
     * @return the _UserRight
     */
    protected UserRight getUserRight() {
        return _UserRight;
    }

    /**
     * @param UserRight the _UserRight to set
     */
    public void setUserRight(UserRight UserRight) {
        this._UserRight = UserRight;
    }




}


